### ISSUE TITLE
Support VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT_KHR

### ISSUE THREAD

**Issue by Jasper-Bekkers** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#104]
Now with the release of the Vulkan Ray-Tracing khr it's becoming quite necessary to be allocate memory with these flags, since at least scratch memory buffers and acceleration structure buffers will need this flag passed in to the memory allocator.

**Comment by adam-sawicki-a** [comment]
Thank you for the suggestion. I already have the plan to add support for `VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT_KHR` on my TODO list and I plan to do it pretty soon, subject to time constraints. I will bump its priority.

**Comment by Jasper-Bekkers** [comment]
Thanks Adam, is it turns out I need this soon (probably) I can take a look / hack something up and contribute back.

**Comment by adam-sawicki-a** [comment]
OK, then let me quickly summarize my plan to see if it fits your needs.

Prerequisites:

- When VK_KHR_buffer_device_address is enabled, `VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT_KHR` flag can be added to any memory allocation, because I don't expect it to cause performance degradation or any other problem.
- Only basic `DEVICE_ADDRESS` flags will be supported and NOT `DEVICE_ADDRESS_CAPTURE_REPLAY`, as those are used only by RenderDoc and other such debugging tools, not by regular Vulkan users.

Plan for implementation:

- Adding flag `VMA_ALLOCATOR_CREATE_KHR_BUFFER_DEVICE_ADDRESS_BIT` which the user can specify if he checked that the extension is available and enabled it.
- When the flag is set, all the `VkDeviceMemory` allocations that COULD potentially hold a buffer with `VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT` will have `VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT_KHR` added to the allocation. Which means:
a) Every memory block that can be used to hold arbitrary resources.
b) Memory allocated for a dedicated resource if the resource is a buffer and has `VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT`.

I think that for your case where you are sure your app will need it, you can simply add `VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT_KHR` to every allocation made by VMA.

**Comment by adam-sawicki-a** [comment]
Hey, I've implemented the support for buffer device address on master branch. Can you please check if it works for you and solves your problem?

**Comment by SaschaWillems** [comment]
Thank you so much for providing this. I'm fiddling around with VK_KHR_ray_tracing which requires this, so this comes at the right time.

Just tested it and it works fine :)

**Comment by lumonix** [comment]
@adam-sawicki-a 
Thank you for adding this!

One possible bug report when testing this:

In Vulkan SDK 1.1.130.0 (linux) VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT is not defined. Only VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT_KHR is defined.

This makes AllocateDedicatedMemory not compile.
(I could provide a fix if that is preferred)

Thanks!

**Comment by adam-sawicki-a** [comment]
You are right, my bad. "KHR" extension version precedes core version and I want to support both, so I use "KHR" version everywhere. I fixed the bug.
