### ISSUE TITLE
Put all definitions in a header file isn't a good idea

### ISSUE THREAD

**Issue by yukunxie** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#108]
1. difficult to read
2. multi-definition errors

**Comment by adam-sawicki-a** [comment]
Multi-definition errors can be fixed by following instructions of proper setup, as described in the documentation chapter "Quick start" > "Project setup".

The so-called "STB-style" single header libraries are a popular solution among C and C++ developers. Although it causes some trouble during development of the library, this form is preferred by many users.

Developing VMA this way was a design decision made at the very beginning.
