### ISSUE TITLE
Doc clarification about VMA_MEMORY_USAGE_CPU_TO_GPU

### ISSUE THREAD

**Issue by mbechard** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#129]
Hey,
The docs state that VMA_MEMORY_USAGE_CPU_TO_GPU should be used for textures that are updating every frame. What is the usage pattern that is being thought of for this case? Is the expectation that the texture will be LINEAR tiling so it can be written to directly and then used by the GPU as-is. Or is it still expected that a buffer will be copied to a texture using OPTIMAL tiling.
More specifically, if I'm doing a vkCmdCopyBufferToImage so that the data ends up in OPTIMAL tiling format anyways, is there any benefit to using VMA_MEMORY_USAGE_CPU_TO_GPU, or should I just use VMA_MEMORY_USAGE_CPU_ONLY for the source of the copy operation?
Thanks

**Comment by adam-sawicki-a** [comment]
Hey,

You are right that the names of VMA_MEMORY_USAGE_ flags are a bit misleading. They date back to before the library was even created, in the very first design phase.

VMA_MEMORY_USAGE_CPU_TO_GPU is intended for resources that are directly written via mapped pointer by CPU and used by the GPU, without performing a copy. With buffers it's quite easy. With textures it's not because you either need to use LINEAR tiling, which may degrade performance when used on the GPU, or need to issue a copy from a buffer.

Which way is faster? That's not easy to predict. Optimal solution would be to implement both and measure, on a variety of GPUs.

1. Create a texture in VMA_MEMORY_USAGE_CPU_TO_GPU, with LINEAR tiling, map and write to it from CPU, read from it on GPU
2. Create a texture in VMA_MEMORY_USAGE_GPU_ONLY with OPTIMAL tiling, a buffer in VMA_MEMORY_USAGE_CPU_ONLY and perform a copy

See also documentation chapter "Recommended usage patterns":
https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/usage_patterns.html

**Comment by mbechard** [comment]
Thanks. I think the flag names are ok. What threw me off is that VMA_MEMORY_USAGE_CPU_TO_GPU doc specially says it's the correct mode for textures that are changing every frame. It would seem to may need to be expanded to note that that's the case if the texture is linear.

**Comment by adam-sawicki-a** [comment]
You are right. I clarified this in few places in the documentation.

Please note that using LINEAR instead of OPTIMAL tiling on some textures may result in slower access on the device, but may still be faster than using explicit transfer. DXVK also uses this method:
https://github.com/doitsujin/dxvk/blob/7b760800b407ee5cc1a62b1906bcdcd2781807ab/src/d3d11/d3d11_texture.cpp#L131

If you want to just transfer from CPU to GPU memory, then please use VMA_MEMORY_USAGE_CPU_ONLY, not CPU_TO_GPU for the source texture.
