### ISSUE TITLE
Issue when integrating with the mimalloc allocator

### ISSUE THREAD

**Issue by Honeybunch** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#139]
The mimalloc allocator https://github.com/microsoft/mimalloc has gained some attention recently and looks to be a promising malloc replacement. However I ran into an issue when trying to integrate with the VMA. 

VMA wants to use an aligned malloc. mimalloc supplies `mi_malloc_aligned` but there is an issue when interacting with `VmaCreateStringCopy`. `mi_malloc_aligned` asserts when the given alignment is less than `sizeof(void*)`. When creating a copy of a string VMA uses an alignment of 1. 

To work around this I made a distinction in vk_mem_alloc.h between aligned an unaligned allocations. The `VMA_SYSTEM_MALLOC` define was renamed to `VMA_SYSTEM_ALIGNED_MALLOC` and a new `VMA_SYSTEM_MALLOC` was added that maps to the system `malloc` by default. The only usage of this unaligned malloc is in `VmaCreateStringCopy`. 

The modified version can be found here: 
[vk_mem_alloc.zip](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/files/4908049/vk_mem_alloc.zip)

I'm not quite knowledgeable enough of the inner workings of the VMA to comfortably post this as a PR as I have no idea if it's a "good idea". It's also been mangled by my personal .clang-format settings which I have yet to undo. If this is an acceptable solution for upstream I can turn this into a pull request. Or if someone else wants to solve this in a different way that's fine by me.

**Comment by adam-sawicki-a** [comment]
If the allocator you want to use doesn't allow an alignment that is accepted by any other, then I would say it should be submitted as a bug to that project.

I think an easy solution would be to just give larger alignment, i.e. calculate `alignment = max(alignment, sizeof(void*))` before passing it to mimalloc. It should just work.

Some side notes:

- I cannot diff your file with base VMA code because it looks like you changed the majority of the code. It looks reformatted. Probably some automated tool reformatted all the code without your knowledge and consent. I recommend to disable such tools when cooperating with other people on some code.
- You seem to base on official VMA release 2.3.0 which is very old code. I recommend to use latest from master branch. It is pretty stable and contains recent fixes and improvements.

**Comment by Honeybunch** [comment]
Thanks for the solid feedback. You're right, It should probably be reported to mimalloc. Your solution is also a lot simpler and is probably what I'll end up doing (after I update my copy of the VMA).

I usually try to keep my code formatted with clang-format. I should probably add some filters to my config to not format header libraries like this. 

This is probably safe to close :)
