### ISSUE TITLE
How to map specific ranges?

### ISSUE THREAD

**Issue by chaoticbob** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#179]
Hi,

Really appreciate all the work that's been done on this awesome library through out the years. 

I'm working on an application that could really benefit from being able to map specific ranges on buffers and subresources on images. I was wondering if there was a recommneded way to use VmaAllocation and VmaAllocationInfo so I can map a range that's local to a buffer or a subresource on an image.

For example, I'd like to od the follow things:
 * I'd like to be able to map chunks of 4K blocks within a 64K buffer
 * Map just the 3rd mip map on an image
 * Map just the 4th slice on an image

I scanned through the source and the docs but couldn't find anything. Did I miss something?

Thanks,
Hai

**Comment by adam-sawicki-a** [comment]
Hi,

There is no such thing in VMA as there is no need for it. Mapping works on a level of whole memory blocks - VkDeviceMemory. Because Vulkan (unlike Direct3D 12) doesn't allow to map the same memory blocks multiple times, VMA maps entire memory block even when you request mapping of a single resource allocated from it, because otherwise you wouldn't be able to map another resource from the same block simultaneously. VMA then returns a pointer adjusted to an offset of a particular allocation.

Similarly, you can just map your entire resource of interest and then move the pointer by an offset to the particular region of your interest, whether it's a 4K block in a buffer or a particular subresource of your image, with offset and size fetched using `vkGetImageSubresourceLayout`.

Would that work for you?

Please note that `vkGetImageSubresourceLayout` provides information eligible for host access via mapped pointer only for LINEAR images, while using LINEAR images is slower than OPTIMAL and usually not needed. It is recommended to prepare your image data in a buffer and then do a buffer-to-image copy (transfer).

**Comment by chaoticbob** [comment]
Hi Adam,

Thanks for the reply. I can definitely just move the pointer around and calculate the necessary offsets per your suggestion.

I know the behavior and limits of `vkGetImageSubresourceLayout` all too well :) 

Cheers,
Hai
