### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by ellipticaldoor** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#182]
I'm getting the following warnings flags when including "vk_mem_alloc.h":

```
-Wundef
-Wunused-parameter
-Wnested-anon-types
-Wnullability-completeness
-Wsign-conversion
-Wunused-variable
-Wmissing-field-initializers
-Wnullability-extension
```

Could be possible that enabling this flags could help and avoid potential bugs?

**Comment by adam-sawicki-a** [comment]
I am sorry, but just as the library documentation says in chapter "Features not supported", it is out of scope of the library to be free of any warnings on any version of any compiler. The library is developed mostly on- and for Windows using Visual Studio 2019.

Many of the warnings are false alarms raised due to multiple configurations available in the code, driven by preprocessor macros, so some parts of the code become dead or expressions become constant in some configurations. I am not going to make the code more complicated just to silence these warnings.

Please feel free to report any real bugs you will find among these warnings.

**Comment by ellipticaldoor** [comment]
Ah! I see, thank you for the explanation
