### ISSUE TITLE
no CMakeLists in release archives

### ISSUE THREAD

**Issue by Unrealf1** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#212]
Is absence of CMaleLists.txt files in release archives intentional? It makes automatic dependency management a bit awkward, I have to manually download these files from the repo

Would be great if future releases included them

**Comment by adam-sawicki-a** [comment]
Last official release was long time ago and didn't use Cmake. CMakeLists.txt was added later during continuous development on the master branch. It will be included in the next release, together with everything you can find on that branch.

I recommend to use the latest code from master branch rather than the official release package. The project is always kept in a good shape, shouldn't cause any problems after updating.
