### ISSUE TITLE
Please reconsider the new memory usage flags

### ISSUE THREAD

**Issue by Novum** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#266]
The new API is extremely confusing. It should not pretend to know better what memory type I need.

E.g. people will start using `VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT` for staging buffers because hey, they are writing only sequentially to it right? And then get handed GPU local host visible memory which is slow to write to, potentially to small for what they want to stage _and_ slow for the GPU to copy from e.g. on AMD where the transfer queue VRAM to VRAM copies are broken.

I don't think it is in the spirit of Vulkan to hide the machine from the user. It just makes it unclear of what's actually going to happen.

**Comment by martin-ejdestig** [comment]
I think I got bit by this.

Investigated a slowdown related to vertex/index buffers that are updated every frame from the CPU. Bisecting lead me to commit that integrated VMA. `VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT` is used for these buffers.

When integrating VMA code creating these buffers was modified to pass `VMA_MEMORY_USAGE_AUTO` and `VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT`. This results in memory with `VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT` which in turn leads to writing to these buffers on the CPU taking a lot longer on both the Nvidia and AMD GPUs I have to test with. For Nvidia it takes ~1.8 times longer and for AMD ~1.3 times longer. (For integrated Intel GPU I have tested with it does not matter since `VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT` is set for the memory type both before and after VMA integration).

I have currently hacked around this by always passing `VMA_MEMORY_USAGE_AUTO_PREFER_HOST` if `VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT` is passed to the buffer creation function.

I have not measured how this affects staging buffers that use the same code path for creating CPU mapped buffers. The hack restores it so same memory property flags are passed before VMA integration since I assume there was a slowdown there as well.

**Comment by adam-sawicki-a** [comment]
I am sorry for delayed response.

@Novum: I understand your point. The purpose of introducing `VMA_MEMORY_USAGE_AUTO*` flags was to make the API of the library as simple to use as possible in basic use cases and for beginners. If you understand caveats like the performance of VRAM to VRAM copy on different hardware queues, you likely want to use `VMA_MEMORY_USAGE_AUTO_PREFER_DEVICE` / `_HOST` or narrow down the choice of selected memory types using e.g. `VmaAllocationCreateInfo::requiredFlags` or `VmaAllocationCreateInfo::memoryTypeBits`.

Answering your specific concerns:

- Access patterns unfriendly to uncached and write-combined memory (other than sequential writes) are very slow regardless of using system RAM of VRAM.
- Sequential writes through a pointer to VRAM going through PCIe Gen 4 are almost as fast as writes to system RAM - same order of magniture.
- If you use graphics or compute queue not copy queue for your copies, they will be fast regardless of copying from system RAM or VRAM.
- If the CPU-visible VRAM is small, Vulkan will either fail the allocation (that will make VMA fall back to system RAM) or return success and migrate something to system RAM silently, which is usually what you want in this case.

See also this article, which is the result of performance experiments we did at AMD:
https://gpuopen.com/learn/get-the-most-out-of-smart-access-memory/

@kvark:

1. I agree with you that if you create a custom pool that ends up in a memory heap with small capacity, it can cause problems. Because we talk about choosing memory type index explicitly, I would recommend to inspect heap sizes first before making the decision or, even better, not using custom pools. Custom pools aren't needed as often as developers use them.
2. I agree with you this is a flaw of the current algorithm. It shouldn't choose `DEVICE_LOCAL` memory in this case. I will fix it.

@martin-ejdestig: I am sorry to hear you experienced decreased performance after integrating VMA. I think your workaround of using `VMA_MEMORY_USAGE_AUTO_PREFER_HOST` is a good solution. However, I also recommend to inspect your code that writes into the mapped pointer, whether it really is a sequential write and not random access or it doesn't involve any reads, even implicit like `pData[i] += a`. Maybe try to prepare the data in a local variable and use `memcpy` to copy them to the mapped pointer and see if it helps the performance.

**Comment by martin-ejdestig** [comment]
> @martin-ejdestig: I am sorry to hear you experienced decreased performance after integrating VMA. I think your workaround of using `VMA_MEMORY_USAGE_AUTO_PREFER_HOST` is a good solution. However, I also recommend to inspect your code that writes into the mapped pointer, whether it really is a sequential write and not random access or it doesn't involve any reads, even implicit like `pData[i] += a`. Maybe try to prepare the data in a local variable and use `memcpy` to copy them to the mapped pointer and see if it helps the performance.

It is sequential. Simple for loop that iterates over data and writes indices and vertices and no modification with `+=` etc. ("Ping pongs" between vertex and index buffer though, if that matters. I tried writing to buffers that were then copied with `memcpy()` before integrating VMA. If I remember correctly it only got slower.)

Anyway, I was just surprised by this. But I also see the value of having `VMA_MEMORY_USAGE_*`.

So... I do not know. I feel that I am only adding noise here, will go back to lurking in the shadows. :)

**Comment by adam-sawicki-a** [comment]
VMA doesn't automatically prefer `HOST_COHERENT` memory. The only difference between `HOST_COHERENT` and non-`HOST_COHERENT` memory is that you need to call flush/invalidate after you write / before you read the memory through a mapped pointer. I don't think this is a big burden. On Windows PC, all GPU vendors provide all memory types that are `HOST_VISIBLE` also as `HOST_COHERENT`. If the platforms you use don't do it, you can just call `vmaFlushAllocation` / `vmaInvalidateAllocation` every time it is needed. There is no need to check if the memory is `HOST_COHERENT`. VMA checks that automatically and in case it is, the function does nothing.

Alternatively, you can request the memory to be `HOST_COHERENT` by adding:
```cpp
allocInfo.requiredFlags = VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
```
This can be freely mixed with other parameters of `VmaAllocationCreateInfo`, like the usage flags. However, I don't recommend this method. If your platform provides a non-`HOST_COHERENT` memory type that meets all your other requirements and is higher on the list of memory types, it my be more efficient.

**Comment by adam-sawicki-a** [comment]
Although not fully documented but rather platform-specific, I would expect `HOST_CACHED` flag to determine what you mentioned: With this flag, CPU accesses to the memory are cached, without it - they are uncached but write-combined. I think `HOST_COHERENT` is less related to that. Possibly, `HOST_COHERENT` is slower in some way because of the overhead of the cache coherency between host and device that must be ensured automatically.

> This question of mine arose precisely because of this: the devices I was looking at had this DEVICE_LOCAL memory type at a lower position than the one that's HOST_COHERENT and not DEVICE_LOCAL. Yet using VMA_MEMORY_USAGE_AUTO, you would get the DEVICE_LOCAL one. Would you still recommend this memory type in this case?

From the memory heaps and types you showed, I would expect:
- Type 0 is the video memory, not accessible to the host. Good to be used for GPU-only resources like color attachment images or sampled images that are uploaded once.
- Type 1 is the system memory, good for staging buffers used as a source or destination of a transfer.
- Type 2 is the CPU-visible video memory, good writing data directly from the CPU and reading them on the GPU, like uniform buffers changing every render frame.
