### ISSUE TITLE
[git] Provide branches named equally to the tags of releases

### ISSUE THREAD

**Issue by tomilov** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#281]
When adding VMA as a submodule of a project one can't specify specific tag to stick to, whereas (e.g.) VulkanHeaders allows this via branches.
Currently `git submodule update`, called after `git submodule add -b v3.0.1 https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator.git external/VulkanMemoryAllocator` results in error "no branch named v3.0.1".
Currently checking out of a repository, that has VMA as a submodule, results in checking out `HEAD` of `master` branch of VMA's repository, if `.gitmodules` doesn't contain specific `branch = ` entry.

**Comment by MattiasLiljeson** [comment]
My understanding is that you want to use VMA as a submodule and pin its version to a specific release.

A submodule is tracked by the parent repo by in each commit saying which submodule commit should be checked out in the submodule. What the '-b' option does in the 'submodule add' command is adding a branch to track, so that you can easily check out the latest commit in that branch in the submodule when running 'submodule update' (by supplying '--remote'), instead of checking out the submodule commit specified in the parent repo commit. In your case, since you seem to want to stick to a certain release, I would simply add the submodule normally, cd down into the submodule, check out the release (tag) in the submodule, cd up to the parent repo, and add that submodule checkout to a commit in the parent repo.

That is of course more work than just adding a submodule with a branch, and checking out the last commit on that branch with the --remote option, but solves the problem without having to create branches for every release.

There are a few options in git for working with submodules which makes life easier which i highly recommend:
- diff.submodule = log (so you get clearer container diffs when referenced submodule commits changed. Instead of SHAs, you will see a log with the changes between the commits).
- status.submoduleSummary = true (so git status gets useful again when a referenced submodule commit changed).
- submodule.recurse = true (automatically check out the commit(s) in the submodule(s) specified by the commit in the parent repo. Fail if there are local modifications in the submodule(s))
