### ISSUE TITLE
vmaBindBufferMemory, vmaBindImageMemory should accept offset since vkBindBufferMemory, vkBindImageMemory do

### ISSUE THREAD

**Issue by manas-kulkarni** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#302]
- Minor
  - Current interface makes it seem like you need VK_KHR_bind_memory2 to provide offsets when binding memory

**Comment by adam-sawicki-a** [comment]
First of all, recommended and easy way to create images and buffers in VMA is using functions like `vmaCreateBuffer` that create a buffer/image, allocate memory for it, and bind them together, all in one call.

If you want to do it separately, then it is recommended to create a separate `VmaAllocation` for each individual buffer/texture you want to bind. Then, if the allocation is part of a bigger block of `VkDeviceMemory`, functions like `vmaBindBufferMemory` automatically apply its offset when binding. This is unlike Vulkan `vkBindBufferMemory`, where you need to specify an offset from the beginning of the memory block. This is why the offset is not needed in VMA interface.

Finally, if you really want to bind a buffer/image to a specific place inside a single `VmaAllocation`, there are functions that accept `allocationLocalOffset` parameter - `vmaBindBufferMemory2`, `vmaBindImageMemory2`. These are separate functions with "2" in their names due to backward compatibility with older, simpler versions.

It is not true that functions `vmaBindBufferMemory2`, `vmaBindImageMemory2` require VK_KHR_bind_memory2 extensions. If you pass `pNext == nullptr`, the base Vulkan function is used for binding and the extension doesn't need to be enabled.

**Comment by manas-kulkarni** [comment]
I agree. As I said, very minor. Function names just give the impression that you need the VK_KHR_bind_memory2 extension for supplying offsets. I close this issue if API change is not possible

**Comment by adam-sawicki-a** [comment]
By the impression do you mean the "2" in function names? This is just a coincidence, I just wanted to create new functions so the old ones retain backward compatibility. If the API was Windows-style, I could call them `vmaBindBufferMemoryEx` 😉

I don't want to change the API so I don't break backward compatibility.

**Comment by manas-kulkarni** [comment]
Yes. Because of the "2" 😀 Anyway, not a problem. Thanks for the explanation
