### ISSUE TITLE
Create Image with Optimal tiling and HOST_ACCESS_SEQUENTIAL_WRITE memory flag

### ISSUE THREAD

**Issue by FuXiii** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#305]
My device support create `VkImage` with `Optimal` tiling, `TRANSFER_DST` usage in format `B8G8R8A8_UNORM`

![image](https://user-images.githubusercontent.com/40132375/206986484-228f9316-39bd-4b13-a211-8a165dde060b.png)

Then, I use pure `Vulkan API` try to create `VkImage`:

![ImageCreateSuccessed](https://user-images.githubusercontent.com/40132375/206985267-e0cfdb73-f56c-4f2f-96be-eb1fa5db0f55.png)
It created successfully

---

and then I try to use `VMA` call `vmaCreateImage` to create image:

![image](https://user-images.githubusercontent.com/40132375/206990376-0d30a2ac-5566-4104-8414-2ae97b21fc2e.png)
![image](https://user-images.githubusercontent.com/40132375/206988434-e199ea38-1a83-4acb-8817-f3f3ab4cc8a2.png)

```CXX
VmaAllocator *vma_allocator = (VmaAllocator *)(this->device->GetVmaAllocator()->GetVmaAllocator());
VkResult result = vmaCreateImage(*vma_allocator, &vk_image_create_info, &alloc_info, &this->vkImage, (VmaAllocation *)this->vmaAllocation, nullptr);
```
the create result return `VK_ERROR_FEATURE_NOT_PRESENT`
![image](https://user-images.githubusercontent.com/40132375/206988753-f4f5ea46-8aaf-440b-bfef-5322d4544521.png)

Why? Is that means if I use `Optimal` tiling, I must use `DEDICATED_MEMORY`?
If I use `Linear` tiling with `HOST_ACCESS_SEQUENTIAL_WRITE` to create image, and then copy some `GPU` domain resource data into it. Is this the correct usage for `Linear` tiling image?

**Comment by adam-sawicki-a** [comment]
Error code `VK_ERROR_FEATURE_NOT_PRESENT` likely means that no memory type was found that would support the combination of parameters you want to use for created image.

I guess the problem is that you pass `HOST_ACCESS_SEQUENTIAL_WRITE` flag. This flag means you want to use `Map` on this image, so VMA will try to find a memory type that is `HOST_VISIBLE`. Likely images with optimal tiling cannot be created in such memory. If you only want to use a copy operation on that image and not `Map`, you don't need `HOST_ACCESS_SEQUENTIAL_WRITE` flag.

**Comment by FuXiii** [comment]
Thank you for your answer~⌯'▾'⌯
