### ISSUE TITLE
Vma c interface issue

### ISSUE THREAD

**Issue by bensam00** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#308]
I have included vk_mem_alloc.h on my c project and in my cmake file i added it as an interface like this 

`add_library(include INTERFACE)`
`target_include_directories(include INTERFACE include)`

while include is the folder where i put my vma header file 
and i added it without `#define VMA_IMPLEMENTATION` as mention in documentation like this 
` #include "include/vk_mem_alloc.h"`

and yet it always gives me 
`undefined reference to 'vmaCreateAllocator'`
when i try to initialize it 

im using fedora 37 with vulkan 1.3

**Comment by adam-sawicki-a** [comment]
"Undefined reference" likely means that you didn't include VMA implementation in your project. Cmake script is provided as an external contribution. Recommended way to use the library is to add "vk_mem_alloc.h" file directly to your project. Please follow instructions from documentation https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/quick_start.html. Long story short, in exactly one C++ source file of your code you need to #include the VMA header preceded by `#define VMA_IMPLEMENTATION` so the internal implementation of the library is compiled. Only then your project will include implementation of functions declared by the header.

**Comment by mr-sihc** [comment]
`mold: error: /usr/lib64/libVulkanMemoryAllocator.a(VmaUsage.cpp.o):(.text): R_X86_64_PC32 relocation at offset 0x1987 against symbol 'vtable for VmaBlockMetadata' can not be used; recompile with -fPIC`
i get this error, i'm already compiling and linking with -fPIC
but its probably the library that didnt compile and link with -fPIC
can you add this to the CMake?

**Comment by adam-sawicki-a** [comment]
This library is developed mostly on and for Windows + Visual Studio. I don't know what is `-fPIC` so I am not sure whether I should add this option to CMake.

Please try to include "vk_mem_alloc.h" directly in your project code, like the documentation recommends, instead of using it as a separate library with CMake and see if it helps on your platform.

**Comment by mr-sihc** [comment]
i did -fPIC mean position independent code
which libraries usually get compiled with

**Comment by juan-lunarg** [comment]
I believe this issue can now be closed with all the CMake fixes made to master.

-fPIC doesn't apply at all anymore now that `GPUOpen::VulkanMemoryAllocator` is a minimal header only library like `Vulkan::Headers`.

The CMake now nicely compliments the existing documentation (https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/quick_start.html) instead of contrasting it by building and enforcing binaries on the user.
