### ISSUE TITLE
Strict mode for testing for mem leaks?

### ISSUE THREAD

**Issue by UltraEngine** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#314]
I had a bit of a scare today when I noticed our memory usage was shooting up rapidly when the program started. I finally realized it was due to these lines:
```c++
vmaMapMemory(device->allocator, allocation, &data);
for (const VkBufferCopy& region : device->storagebuffer[n]->modifiedregions)
{
	memcpy(((char*)data) + region.dstOffset, device->storagebuffer[n]->bufferdata->Data() + region.srcOffset, region.size);
	vmaFlushAllocation(device->allocator, allocation, region.dstOffset, region.size);
}
vmaUnmapMemory(device->allocator, allocation);
```
It did not make sense to me how that could cause a memory leak. I eventually realized the application memory usage would level off after about ten seconds and then stayed perfectly flat.

I'm assuming the memory allocator has a preference to allocate new memory until some threshold is reached, and that's what was causing the behavior I saw. I was wondering if there is a more strict setting I can use for our debug builds, to make it easier to detect memory leaks? Thanks.

**Comment by adam-sawicki-a** [comment]
I am not sure I understand your question. Calling Map, Unmap, Flush doesn't allocate any memory, so memory usage should not increase due to the code you showed.

What platform - operating system and GPU do you use?

If you want to limit maximum amount of memory that can be allocated by VMA in particular heaps, you can use `VmaAllocatorCreateInfo::pHeapSizeLimit`.

I also recommend to monitor memory usage through statistics API to find out when exactly is memory usage increasing:
https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/statistics.html

To detect actual memory leaks, make sure `VMA_ASSERT` macro is defined to something that triggers an error. Then, unfreed allocations are detected and reported on exit.

**Comment by UltraEngine** [comment]
This is on a GEForce 1060M on Windows 10.

Thank you for the information. I will look into this more closely.
