### ISSUE TITLE
Suggestion: Create a new release

### ISSUE THREAD

**Issue by tvoeroes** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#318]
Hello, I was using the `v3.0.1` version of the library and was getting some Vulkan validation errors. I tracked the errors back to an issue that was fixed in 1022be64 (22. Jun 2022). In my opinion, such a fix deserves a version bump.

**Comment by adam-sawicki-a** [comment]
New release is planned, but for now I recommend to always use latest code form the main branch. It is kept in a good state, with no broken builds, unfinished or untested features.

**Comment by scribam** [comment]
Having a new release will make the changes available for the Vulkan SDK. In the release notes https://vulkan.lunarg.com/doc/sdk/1.3.243.0/windows/release_notes.html, part "SDK Components", you can see the tag 3.0.1 is used for AMD Memory Allocator.

**Comment by juan-lunarg** [comment]
Note. We are going to use current ToT (https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/commit/0e89587db3ebee4d463f191bd296374c5fafc8ea) for the upcoming Vulkan SDK. Based on input from @adam-sawicki-a and @neurotok.

**Comment by juan-lunarg** [comment]
Note: Vulkan SDK 1.3.250 uses 0e89587db3ebee4d463f191bd296374c5fafc8ea instead of the 3.0.1 tag.

If there is a new release of Vulkan-Memory-Allocator the gpuopen webpage should also be updated. It's currently listing 3.0.0 as the latest release.

https://gpuopen.com/vulkan-memory-allocator/

![image](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/assets/114601453/caa41ede-4a7b-4e3a-b107-080037dde4d1)

Considering we release

**Comment by matthew-rister** [comment]
> New release is planned, but for now I recommend to always use latest code form the main branch. It is kept in a good state, with no broken builds, unfinished or untested features.

If the main branch is kept in a good state, I don't understand why it's difficult to create a new release. This somewhat frustrating because the official documentation mention APIs like [vmaCopyMemoryToAllocation](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/group__group__alloc.html#ga11731ec58a3a43a22bb925e0780ef405) which is unavailable in 3.0.1. Also, for users of vcpkg, I don't believe there is an option to upgrade a port based on a specific GitHub commit. Even if there were, it's unclear what commit to use.

**Comment by adam-sawicki-a** [comment]
What is left to do before calling it a new release is mostly CI build for Linux. Builds on Travis CI stopped working more than a year ago:
https://app.travis-ci.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator
Any help in setting up some free CI builds for Linux is welcome. Would GitHub Actions work? It doesn't need to launch any GPU workload, just test if the code compiles. Preferably on both Clang and GCC.

**Comment by adam-sawicki-a** [comment]
A new release has been tagged: https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/releases/tag/v3.1.0

I am sorry it took so long. I will try to create new releases more frequently whenever there is a major fix or addition to the library code.
