### ISSUE TITLE
vmaMapMemory triggers validation layer warning on Intel HD 620

### ISSUE THREAD

**Issue by victorbush** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#34]
When mapping a buffer with `vmaMapMemory`, a validation layer warning is triggered:

```
validation layer: Object: 0xb (Type = 8) | Mapping an image with layout VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL can result in undefined behavior if this memory is used by the device. Only GENERAL or PREINITIALIZED should be used.
```

The buffer is created with `vmaCreateBuffer`:

```
VkBufferCreateInfo bufferInfo = {};
bufferInfo.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
bufferInfo.size = size;
bufferInfo.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT;
bufferInfo.sharingMode = VK_SHARING_MODE_EXCLUSIVE;

VmaAllocationCreateInfo allocInfo = {};
allocInfo.usage = VMA_MEMORY_USAGE_CPU_ONLY;

auto result = vmaCreateBuffer(_allocator, &bufferInfo, &allocInfo, &buffer, &allocation, nullptr);
```

Then I map the memory with `vmaMapMemory`:

```
void* data;
vmaMapMemory(_device.GetAllocator(), allocation, &data);
memcpy(data, RenderMesh::GetVertices().data(), (size_t)bufferSize);
vmaUnmapMemory(_device.GetAllocator(), allocation);
```

When `vmaMapMemory` is called, the validation layer warning is triggered 3 times. The call to `vmaMapMemory` succeeds and works as expected, it just triggers validation warnings every time its called.

When I use `vkCreateBuffer`, `vkAllocateMemory`, and `vkMapMemory` to handle the buffer creation and memory mapping instead of the vma library, the warning is not triggered.

This happens on a Surface Laptop with Intel HD Graphics 620.
Windows 10 Pro x64
Driver version: 24.20.100.6136
Also tried driver: 24.20.100.6229

This does not happen on my discrete NVIDIA GPU, so probably related to the Intel HD 620? I'm still new to Vulkan, so I apologize if I missed something.

**Comment by victorbush** [comment]
The strange thing is I'm not mapping an image, it's just a buffer for vertex data (VkBuffer as opposed to VkImage). So I was confused why the validation layer was talking about mapping an image.

**Comment by devshgraphicsprogramming** [comment]
Then validation layer has a bug.

But again these are Intel drivers on Windows :')

**Comment by victorbush** [comment]
Ok thanks. I also found it happens with the sample exe provided with the vma library as well, so its not limited to my program. So potentially a driver issue.

**Comment by adam-sawicki-amd** [comment]
I can imagine how this happened. Long story short: I think it's neither bug in VMA nor in driver, of Vulkan validation layer. It's just a warning that can be safely ignored.

Full story:

Intel GPU has unified memory, with just one memory heap and two memory types. Objects so different as depth-stencil image `GPU_ONLY` and staging buffer `CPU_ONLY` end up in the same memory type, and possibly in the same `VkDeviceMemory` block.

Now comes the mapping. You want to map just your buffer, but Vulkan (as opposite to DX12) doesn't allow to map same memory block twice, so VMA always maps entire `VkDeviceMemory` block, just in case you want to map different object inside of it simultaneously. Validation layer detects that there is an image with `LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL` inside of it and issues a warning.

The warning says *can result in undefined behavior if this memory is used by the device* - but it won't be, because you really just access your buffer with mapped pointer. So the warning can be safely ignored.

I added this warning to ignores and documented it, in "development" branch.

Alternatively, if you want to get rid of this warning, you can try to create your depth-stencil images with `VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT` flag (which is recommended anyway), or you can create custom `VmaPool` to place your buffers which you want to map separate from GPU-only resources.

**Comment by victorbush** [comment]
You nailed it - I used VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT when allocating my depth buffer images and no longer got the validation warning. Thank you!
