### ISSUE TITLE
Is possible to destroy the VmaAllocator without it trying to make any Vulkan calls.

### ISSUE THREAD

**Issue by egdaniel** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#35]
For our rendering engine, the client supplies us with the VkDevice that they want us to use for drawing. We support an API to abandon our rendering context which essentially means we will clean up all our internal memory, but will not make calls to the underlying graphics api (GL, Vulkan). This is needed in case the client deletes the VkDevice or decided it wasn't trustworthy anymore to call into the driver etc. Obviously this leaks GPU objects, but we're fine with that.

So this leads to the question, is it possible for us to destroy the VmaAllocator in a way that will free its local memory, but not make any Vulkan calls since the VkDevice may no longer be valid?

**Comment by adam-sawicki-amd** [comment]
This is not something that the library was designed for. By design, lifetime of `VmaAllocator` should be scoped inside of lifetime of `VkDevice`, just as lifetime of any `VmaAllocation` object, as well as `VkDeviceMemory` blocks managed internally by the allocator, is scoped inside lifetime of the allocator.

Destroying Vulkan device object without notifing code that uses it, as well as leaking memory or API objects looks like bad software design. Even in case of Vulkan device loss, it's still possible to properly destroy all its objects.

If you really want to add this feature, possibly the easiest way is to fill `VmaAllocatorCreateInfo::pVulkanFunctions` with pointers to your own functions, which you implement to either dispatch the call to real Vulkan function or discard it in case you lost access to Vulkan device.
