### ISSUE TITLE
Offer option to use aliased named string with VMA

### ISSUE THREAD

**Issue by alecazam** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#377]
Our strings all go through an Immutable pool, so don't need to be copied.  Would be nice to have a #define option for this.  It was easy enough to comment out calls to vmaFreeString and vmaCopyString for the names, but formalizing this would be good.

**Comment by adam-sawicki-a** [comment]
I am sorry, but I don't want to introduce this extra feature in the name of avoiding feature creep. I understand your names are immutable, but I expect most users to build these names dynamically, based on e.g. name of a texture file like "Models\Characters\MyTexture.dds", or formatted from data like "MyRenderTarget 10 3840x2160".

Assiging names to allocations and custom pools is a debugging feature, just like setting object names and labels in VK_EXT_debug_utils. I expect most users, especially game developers, to strip out this functionality in the final build of the application. Thus, its performance and memory usage is not critical.

Are you sure your application will not need dynamically formatted names in the future as it grows?

Did you observe any memory or peformance issue due to VMA making copies of these strings?

Please note that `vkSetDebugUtilsObjectNameEXT` also doesn't offer an option for using externally-owned strings as names.

**Comment by alecazam** [comment]
No problem, just a suggestion.  We have all mutable string turned into immutable.  You can also alias immutable string if you don't have hotloading.   So with say 5000 uniform buffers all called PerObjectUniforms, we save a lot of allocations.  And with around 20000 unique resources it adds up.  It was easy enough to mod the sources, so no problem if this isn't formalized.

**Comment by alecazam** [comment]
The original reason I was doing this, is that we were hitting UTF8 asserts (see bug about signed char) when doing Json dumps.  But something is turning strings > 32 chars into 38 chars with the last 5 chars garbage.  So I wanted to see if aliasing our immutable strings and avoiding all copies would help.

**Comment by alecazam** [comment]
I found out what was corrupting our strings.  It was #define sprintf _sprintf.   Apparently Microsoft decided that _sprintf shouldn't null terminate on overflow, so it was turning all our strings sprintf-ed to a name[32] into garbage.  Still keeping out code to alias out strings though.  No point in copying them repeatedly, and they're typically repeated strings anyways.
