### ISSUE TITLE
Validation error (VkMemoryRequirements::alignment) in v2.3.0

### ISSUE THREAD

**Issue by AlejandroCosin** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#394]
Hi,

I am using VMA v2.3.0, I have been reported the Vulkan Validation error happening in one example of our SDK:

`Validation Error: [ VUID-vkBindBufferMemory-memoryOffset-01036 ] Object 0: handle = 0x944a2c0000000039, type = VK_OBJECT_TYPE_BUFFER; Object 1: handle = 0xa21a4e0000000030, type = VK_OBJECT_TYPE_DEVICE_MEMORY; | MessageID = 0xd76a7d6b | vkBindBufferMemory(): memoryOffset is 0x14b2c8 but must be an integer multiple of the VkMemoryRequirements::alignment value 0x10, returned from a call to vkGetBufferMemoryRequirements with buffer. The Vulkan spec states: memoryOffset must be an integer multiple of the alignment member of the VkMemoryRequirements structure returned from a call to vkGetBufferMemoryRequirements with buffer (https://vulkan.lunarg.com/doc/view/1.3.261.1/windows/1.3-extensions/vkspec.html#VUID-vkBindBufferMemory-memoryOffset-01036)`

I was able to gather some information. After four allocations of sizes 1144808, 1144808, 211668 and 211668, there is one allocation of 4194304 bytes. In `bool VmaBlockMetadata_Generic::CheckAllocation` (vk_mem_alloc.h), the line
        `*pOffset = VmaAlignUp(*pOffset, allocAlignment);`
has `pOffset = 1356488` and `allocAlignment = 4`, making `pOffset` remain the same value (1356488). The value of `allocAllignment` comes from `void VmaAllocator_T::GetBufferMemoryRequirements`, from the line
        `(*m_VulkanFunctions.vkGetBufferMemoryRequirements)(m_hDevice, hBuffer, &memReq);`

This value (4) ends assigned to the field `VmaAllocationInfo::offset` of the struct generated in the allocation. Calling `vkBindBufferMemory` with this offset triggers the validation error, as the offset within the memory should be a multiple of `VkMemoryRequirements::alignment` (16 in this case).

Do you think this could be incorrect usage of your library, or maybe incorrect information provided by the driver? This was reported on a RTX 3070 with NVIDIA driver 546.33.

Best regards and thanks in advance

**Comment by adam-sawicki-a** [comment]
Hi,

From your description, it looks like a driver bug. The line you quoted `(*m_VulkanFunctions.vkGetBufferMemoryRequirements)(m_hDevice, hBuffer, &memReq);` is calling `vkGetBufferMemoryRequirements`, which should return alignment required for a specific buffer. VMA respects that, as you debugged through the whole path. Maybe returned value is too small for that buffer or maybe this is a false alarm, a bug in Validation Layers.

Please first make sure to update graphics driver and Vulkan SDK. Please also use latest version of VMA from "master" branch, as v2.3.0 you mentioned and even last official release v3.0.1 is very old. There have been many bug fixes and improvements since then, while backward compatibility is mostly preserved, so upgrade should be easy.

**Comment by AlejandroCosin** [comment]
Thanks a lot for your help,

I got confirmation the driver was reporting wrong information, I am closing this issue as it turned out to be a false positive.
