### ISSUE TITLE
Introduce a CMake option which allows VMA_DEBUG_LOG to be enabled easily

### ISSUE THREAD

**Issue by IAmNotHanni** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#437]
I would like to talk again about https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/130. In that ticket, we talked about that VMA could automatically tell you which allocations are not freed in case you have a memory leak.

Currently, the code looks like this:

https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/blob/ceb6aeafb0ad1264a37010091123cd8f17cb1364/include/vk_mem_alloc.h#L3020-L3032

This means that for me to use this,
1. I must know that this exists (it's not mentioned in the docs?)
2. Incomment the code (and remove line above)
3. `#define VMA_DEBUG_LOG` in my code.

In my opinion, this code should be uncommented and an option like `ENABLE_VMA_DEBUG_LOG` should be exposed as CMake option (turned off by default), because knowing which allocations are unfreed is one of the central problems which comes up during development. In my opinion, this feature is too valuable to be hidden like this in the library, and it affects not only the development of VMA itself, but also any code base which uses VMA as a library. Also, it should be mentioned in the docs.

Once enabled, it's very nice to see the names of the unfreed allocations when using `vmaSetAllocationName`.

What do you think?

**Comment by IAmNotHanni** [comment]
A fix could look like this:

```cpp
#ifndef VMA_DEBUG_LOG_FORMAT
   #define VMA_DEBUG_LOG_FORMAT(format, ...) do { \
       printf((format), __VA_ARGS__); \
       printf("\n"); \
   } while(false)
#endif

#ifndef VMA_DEBUG_LOG
   #ifndef VMA_ENABLE_DEBUG_LOG
      #define VMA_DEBUG_LOG(str)
   #else
      #define VMA_DEBUG_LOG(str)   VMA_DEBUG_LOG_FORMAT("%s", (str))
   #endif
#endif
```

But I am not sure where to put the CMake option in the .cmake file. Preferably it would be an option for the library itself, not the sample application.

**Comment by adam-sawicki-a** [comment]
Macros `VMA_` are part of library Configuration that should be performed by predefining selected macros before the library implementation is included. It can be done by putting specific `#define` in the code before `#include` of the library, or by using predefined macros in compiler options (`-D`).

You are right that the macro for reporting memory leaks is worth mentioning in the documentation. I updated the documentation - "Configuration" page.

However, to avoid feature creep, I don't want to extend this code further, add new macros, or Cmake options. This code was already extended recently by separating `_LEAK_` macros from `_DEBUG_` macros. I still consider it a debug feature.

I think it is better to avoid memory leaks e.g. by using some kind of smart pointers. Having memory leaks as "one of the central problems which comes up during development" suggests a need for higher-quality code that uses VMA rather than a need for mode debugging features inside the library.

Proposed implementation of `VMA_DEBUG_LOG_FORMAT` macro that is commented our is just a proposal/example. User may want to use something else than the system `printf` function that prints to the standard output. I don't think this or any other specific implementation should be provided by the library.
