### ISSUE TITLE
Warning generated using validation layer when running on IGP

### ISSUE THREAD

**Issue by reduz** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#64]
I am getting this warning when running on Intel IGP (issue filled originally for validation layers here):

https://github.com/KhronosGroup/Vulkan-ValidationLayers/issues/990

Still, I think I am doing nothing wrong. It seems this is due to the AMD memory allocator using the same memory for images (where I specify GPU as a hint) as the staging buffer.

I had to harcode disabling this warning, but I think this situation should be resolved.

**Comment by adam-sawicki-amd** [comment]
This warning is expected when using VMA and just should be ignored. It is already known issue, documented in chapter "General considerations" > "Validation layer warnings"

https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/general_considerations.html#general_considerations_validation_layer_warnings

If Vulkan allowed to map memory on resources, not on memory blocks, or allowed nested mapping thread-safe and reference counted internally (like Direct3D 12 does), VMA wouldn't need to map entire blocks. If Vulkan didn't have a limit on maximum number of allocations, as small as 4096 (like there isn't in Direct3D 12) and there was no performance penalty for putting each resource in a dedicated allocations, allocator would be needed. But because we don't have either, I can't see any way to solve it in VMA.
