### ISSUE TITLE
Resize Buffer?

### ISSUE THREAD

**Issue by kklouzal** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#86]
Is there functionality to resize a buffer or do we need to `vmaDestroyBuffer` and subsequently `vmaCreateBuffer` when we need to adjust the size of a buffer?

**Comment by adam-sawicki-a** [comment]
There is no possibility to adjust the size of a buffer, or any other parameter of a buffer or an image once it's created e.g. pixel format. You need to recreate new one.

But because buffer is just a sequence of bytes, if you need a smaller one you can just use a piece of an existing, larger buffer, possibly with some offset.

**Comment by devshgraphicsprogramming** [comment]
You'd usually solve this with a general purpose virtual address space allocator (offset+size) outside of VMA, however that would only be useful for dynamic UBOs and SSBOs, not possible to resize a native-VkBuffer (unlike OpenGL the API will not update all the bindings automagically).
